### ISSUE TITLE
Can't find example data

### ISSUE THREAD

**Issue by joelnitta** [ConesaLab/tappAS#11]
I don't know if this is just me not looking hard enough, but I can't find the example data files (experimental design file and expression matrix file) used in the tutorial video. Could these either be mentioned in the github README and the documentation on the tappAS website, or made available if they aren't already?

Thanks!

**Comment by aarzalluz** [comment]
Hi @joelnitta,

Thank you for using tappAS! 

The tutorial design and expression matrix files are the same files used in tappAS' Demo project. Our [Installation PDF](https://app.tappas.org/resources/downloads/install.pdf) contains the exact steps you need to follow to create one, and this is the dataset that we generally recommend for users to try out the application. It is also the same dataset that is used in our recently published [tappAS paper](https://genomebiology.biomedcentral.com/articles/10.1186/s13059-020-02028-w), were you can find more examples of analysis, results, plots generated by the application, etc.

In the ISMB2020 tutorial, we used a whitelist to filter transcripts beforehand and make a lighter instance of tappAS to be able to run analysis fast during the hands-on, and this data files were only made available to tutorial attendants. All tutorial recordings and data will be made available to the public after the ECCB2020 virtual conference, however, you're welcome to follow the tutorial using the Demo project. Alternatively, you could wait until we release the complete tutorial recording, data and documentation. We will advertise it via Twitter and include the details on how to access it in the GitHub README.

Best,


Ángeles

**Comment by aarzalluz** [comment]
I'm closing this issue now, but feel free to contact us if you have any further questions or encounter a problem. We're happy to help!

Ángeles

**Comment by joelnitta** [comment]
Thanks for explaining! I did not notice that in the PDF.
While it is great to be able to play with the example data in tappAS, I think it would also be helpful to make the example files easily available for users to troubleshoot their data format. I suppose that is what you will do with the ISMB2020 tutorial data eventually.

**Comment by aarzalluz** [comment]
Hi @joelnitta,

First, sorry about closing the issue too early. I reopened it because I figured it would be best to have all info here in case anyone else needs it. I'll close it again once you confirm that you could find the files :)

We took your suggestion into account, and now provide the example data files from the ISMB tutorial, together with the hands-on exercises. You can download them by clicking [here](https://app.tappas.org/resources/downloads/tutorials/tappAS_projectData.zip). We have also added a [FAQs section](https://app.tappas.org/faqs/) to the tappAS website. The first Q is about how to find **additional documentation for tappAS**, and the links to the ISMB tutorial video and data files. It's still a work in process, so if you ever read it, we would be thankful for any feedback you may want to give us.

Ángeles

**Comment by joelnitta** [comment]
Thanks for being so thoughtful! I was able to find and download the example data. Just a suggestion though: you might consider putting a link to the example dataset in the "Downloads" section of the webpage to make it even easier to find.
