### ISSUE TITLE
Multiple sample isoAnnot GFF3 

### ISSUE THREAD

**Issue by MustafaElshani** [ConesaLab/tappAS#13]
Hi Guys 

I'm new to bioinformatics and trying to analyse some nanopore data with tappAS. I have been researching methods to analyse polyA tail usage and came across tappAS.  Currently I have 8 samples from human cell lines and I have taken them through FLAIR collapse, SQANTI3 and isoAnnot generating separate tappAS ready GFF3 files however I'm kind stuck on inputting these separate GFF3 files into tappAS. the samples consist of replicates and different conditions. Any advise and help would very much be appreciate it

**Comment by aarzalluz** [comment]
Hi @MustafaElshani,

We recently added a [FAQs section](https://app.tappas.org/faqs/) to the tappAS website in which we describe how to solve your problem:

> The best way to use tappAS is to generate one transcriptome for all sequenced samples. To do this, users should pre-process all SMRT cells together using IsoSeq3, and then run SQANTI3 on the output of this joint run. IsoSeq3 documentation contains more info on how to merge SMRT cells -typically all users will need to do is merge the output of the refine command, and then repeat the clustering step. See the IsoSeq3 documentation IsoSeq3 documentation for details.

The same applies to Nanopore data: you'll need to pool all your reads together and process this merged dataset using FLAIR, SQANTI3 and IsoAnnotLite, as you did before, in order to generate a single transcriptome GTF (and GFF3 for tappAS) file for your experiment.

Please consider the second part of the answer we provide in the FAQs section about SQANTI3-guided filtering of your transcriptome:

>WARNING: note that the QC report produced by SQANTI3 can help you make informed decisions about isoforms that might be false positives or low quality, and we strongly advise you to remove them from your transcriptome before you continue your analysis. We recommend reading the SQANTI paper to get a better idea of how to produce a high-quality, curated transcriptome.

Best,

Ángeles
