### ISSUE TITLE
Experimental design

### ISSUE THREAD

**Issue by rsalz** [ConesaLab/tappAS#14]
From what I understand, there must be at least 2 replicates for each condition in the experimental design file. I only have one replicate per condition. Does this mean I can't use tappas?

**Comment by aarzalluz** [comment]
Hi @rsalz,

Indeed, tappAS analyses are based on methods that require replicates to produce statistically significant results, so having no replicates means that you won't be able to use tappAS. 

If having no replicates is due to quantifying with long reads, I would suggest creating one transcriptome for all of your samples, i.e. pooling all long read samples and processing them together using IsoSeq3 + SQANTI3, and then finding matching short-read RNA-Seq data for quantification using kallisto, RSEM, and similar tools. You'll just need to use the long read-generated GTF file as your reference transcriptome.

Best,

Ángeles

**Comment by aarzalluz** [comment]
Hi @rsalz,

Please let me know if you need any further assistance with this, or if you have resolved the issue.
