### ISSUE TITLE
 Error in dataset[, grep(gg, factor)] : subscript out of bounds

### ISSUE THREAD

**Issue by CS791** [ConesaLab/tappAS#17]
HI!

I was running tappAS pipeline for rice and got the following error:
" 20:11 - Processing  0  transcript expression data rowsFiltering out low count features...
20:11 - Error in dataset[, grep(gg, factor)] : subscript out of bounds
20:11 - Calls: tappas_filterNormalize -> filtered.data -> as.matrix
20:11 - Execution halted
20:11 - Input matrix Filter/Normalization script ended. Exit value: 1
20:11 - [ERROR] Unable to filter/normalize expression matrix."

I will appreciate if you provide any suggestions.

Thank you
Best regards

Saurabh

**Comment by aarzalluz** [comment]
Hi Saurabh,

From reading the error message, it appears that all your transcripts have expression below the low filtering threshold you provided upon project creation, and they are all being filtered out.

This could be either because you set the threshold to a value that is too high. What is the threshold value you are using? If you have not changed tappAS' default threshold, the fact that all your transcripts are being removed could be due to errors in transcript quantification. Have you checked whether your transcripts have any non-zero counts?

I cannot really say anything else from the error message -however, if you give us some more information on how you quantified isoform expression on your rice transcriptome and look further up in the log to see if there is anything else that looks suspicious we will probably be able to troubleshoot your analysis a little bit better.

Best,


Ángeles

**Comment by CS791** [comment]
Hi! Ángeles

Thank you for your reply. I used the default threshold for filtering. Yes, I also concluded the error is due to my quantification analysis, since its is not working with other tools as well. Anyways I am reanalyzing my quantification using salmon, and will see if it works. If I get any error I will write again. 
One more things I want to confirm. Does tappAS works fine without having any replicates in RNA-Seq data?

Thanks!

Best regards

Saurabh

**Comment by aarzalluz** [comment]
Of course! I am closing this issue now, but do not hesitate to open a new issue if you have any more problems with tappAS.

In addition, keep in mind that tappAS does not work without RNA-Seq replicates -all of our statistical analyses require at least two replicates per sample. Otherwise, no reliable expression-based results can be inferred from the data.

You can find more useful information in the [FAQs section](https://app.tappas.org/faqs/) in our website.

Best,


Ángeles
