### ISSUE TITLE
Feature Analysis Error

### ISSUE THREAD

**Issue by alexanderkzee** [ConesaLab/tappAS#21]
I attempted to run the features analysis on tappAS, but I am getting no content in the table. I took a look into the logs and found this error:
11:34:17.394 Error in `.rowNamesDF<-`(x, value = value) : invalid 'row.names' length
11:34:17.394 Calls: Favored_tappas ... row.names<- -> row.names<-.data.frame -> .rowNamesDF<-
11:34:17.394 Execution halted
11:34:17.394 Differential Feature Inclusion Analysis script ended. Exit value: 1

I had one warning when I first ran the script stating
11:34:13.076 Warning message:
11:34:13.076 package 'MASS' was built under R version 3.6.2

Any suggestions?

**Comment by aarzalluz** [comment]
Hi @alexanderkzee,

Thank you for reporting this! We realized that the error was due to a bug in the tappAS' code that prevented the DFI analysis in time series from working correctly.

We just uploaded a new release of tappAS ([version 1.0.7](https://github.com/ConesaLab/tappAS/releases/tag/v1.0.7)) including a solution for your problem. Please, try it out and let us know if it works now!

Best,

Ángeles

**Comment by aarzalluz** [comment]
User confirms fix via email, closing issue.
