### ISSUE TITLE
running tappAS on computing cluster

### ISSUE THREAD

**Issue by abrantesas** [ConesaLab/tappAS#26]
Hello, 
I am running tappAS on my desktop but I am also interested in trying to set it up to run on a computing cluster where I would use MobaXterm with X11 forwarding. Has anyone gotten this to work? Is it something I am going to need an administrator to set up?

I updated R and and try to run the jar file. I get several lines of this error.

(java:7507): dconf-CRITICAL **: 15:27:07.080: unable to create directory '/run/user/227900/dconf': Permission denied.  dconf will not work properly.

I tiny window opens that I can close then the main tappAS window opens. If I try to run new project I get the error and tiny window again. 

I will contact the administrator but I am wondering if you have any advice on how to proceed.

Thanks!
Anthony

**Comment by aarzalluz** [comment]
Hi @abrantesas,

Unfortunately, tappAS is not conceived as an application that needs to be run on a computing cluster. You could, in theory, run it as long as it is on a single node with as much RAM as you require, but since tappAS generally runs smoothly on any laptop or computer with 8GB RAM or more, we have never had the necessity to try that out.

The error you report seems to be due to tappAS trying to create the `tappasWorkspace` folder, which is done when the first project is created. Then, every time you create a project, tappAS will automatically create a new folder to store project information and results. Since tappAS is designed to work on local machines, it will, by default create the folder in your home directory. We're uncertain as to where that home will be on a computing cluster, but it seems that you do not have permissions there, and that's why you're getting an error.

Regardless, tappAS cannot be run on OpenJDK. Perhaps you could request the installation of Java8, and try then?

Best,

Ángeles

**Comment by aarzalluz** [comment]
@abrantesas Let us know if you need to follow up on this. Otherwise, we'll close the issue. Thanks!

**Comment by aarzalluz** [comment]
Closing unless user reopens to update.

**Comment by abrantesas** [comment]
I'm not pursuing getting it to run at the moment but may come back to it. I am currently unable to load all of our data without filtering and I have 32GB RAM on my desktop. My gff3 file is over 6GB.

**Comment by abrantesas** [comment]
Thanks for the help!
