### ISSUE TITLE
tappAS application on Windows 10 OS

### ISSUE THREAD

**Issue by JamalEH** [ConesaLab/tappAS#3]
Dear team,
Thank you for the great tool tappAS! I am so excited to give it a try!

I download the installation folders and the tappas.jar file on my computer (Windows 10 OS) and from within the command line I run the following command java -jar tappas.jar
The application opens but with a warning regarding the existence
![Screenshot (50)](https://user-images.githubusercontent.com/52461533/83124677-cc583600-a0d6-11ea-83a2-b1df2efb46bf.png)
 of the Rscript executable file. Please consider the attached screen shoot to get a better idea on the problem.

I will be thankful if you can help me solving this problem!

Kind regards,
Jamal.

**Comment by psalguerog** [comment]
Dear Jamal,

The emerging window you are seeing it is a warning for Windows users. You have to indicate your Rscript file in order to run tappAS. To solve it, you have to click on the [...]  button and look for the "RScript.exe" file. tappAS will only ask for this path once: after you provide it, the application will detect it automatically anytime you execute it.

It usually can be found in the following pathway:
"C:\Program Files\R\R-3.6.1\bin\RScript.exe". However, it depends on the version of R you have and your installation folder.

If you do not have R installed, you can find it on the R website: https://www.r-project.org/. Furthermore, there are some R packages you need to install before running tappAS. The app will try to install them automatically, but if it takes very long or generates an error, you can install them following the instructions in tappAS installation file: https://app.tappas.org/resources/downloads/install.pdf

You will also need RStudio to run the code.

I hope this helps to solve your problem.

Regards,
Pedro Salguero

**Comment by JamalEH** [comment]
Dear Pedro!
Thank you so much for your detailed answer!

Following your instructions the problem got solved! 
You can close this issue then.

Kind regards,
Jamal.

**Comment by psalguerog** [comment]
Thank you for the message, Jamal.

If you have any other problems, do not hesitate to contact us.

Regards,
Pedro Salguero
