### ISSUE TITLE
No transcripts in the GTF target annotation file were annotated after running IsoAnnot

### ISSUE THREAD

**Issue by Dongxu-Zheng** [ConesaLab/tappAS#32]
Hi, Thanks for developing this great software!
I have two Pacbio Isoseq data and I would like to use IsoAnnot for annotation. But after running IsoAnnotLite_v2.7.0_SQ3.py, I didn't get any result. The following are the result I got:

·A total of 0.00 % of transcripts in the GTF target annotation file (0 of 85481) were annotated because they matched a transcript ID in the GFF3 source annotation file (SQANTI FSM and ISM).
                ·A total of 68.91 % of transcripts in the GTF target annotation file (58907 of 85481) do not match any of the transcript IDs in the GFF3 file (SQANTI novel transcripts).
                        ·0.00 % of them (0 of 58907) were annotated by positional feature transference.
                        ·Annotated novel transcripts represent 0.00 % (0 of 85481) of transcript from the GTF target annotation file.

                Global statistics:              ·A total of 0.00 % of transcripts in the GTF target annotation file (0 of 85481) were annotated (at least one feature transferred).
                ·Did not annotate 31.09 % of transcripts (26574) because they do not have gene information in GFF3 source annotation file.
                ·Did not annotate 0.00 % of transcripts (0) because no annotations were retrieved by positional feature transference.

I used the Homo_sapiens_GRCh38_Ensembl_86.gff3 as the annotation file. My reference genome and annotation gtf file are coming from gencode website.
I am not if this is normal or not. Thanks for any suggestions and help!

Cheers,
Dongxu

**Comment by aarzalluz** [comment]
Hi, @Dongxu-Zheng

It is quite normal for transcript IDs to not match between transcriptomes, as they change between reference versions. However, IsoAnnotLite requires correspondence between genomic positions and/or gene IDs to transfer functional features to long read-defined isoforms. It seems to me that the GENCODE reference genome and GTF that you used are not compatible with ENSEMBL in neither of these aspects. 

The solution would be to use a genome annotation and GTF for ENSEMBL to create your transcriptome, that is, from the beginning of your pipeline, or **at least** (*) to run SQANTI3. This will ensure that the long-read transcripts are matched to ENSEMBL genes and genomic positions. Then, you may use IsoAnnotLite to generate a functional annotation.

_**(*)** Note that, depending on the method you used to generate your transcriptome from long reads, you may also need to re-run the pipeline using the ENSEMBL genome and GTF. I would give re-running SQANTI3 with ENSEMBL reference files a go, but if it doesn't work, you'll need to start from scratch._

Let me know if this solved your problem so that we can use this info to improve support/documentation of our tools.

Best,


Ángeles

**Comment by Dongxu-Zheng** [comment]
> Hi, @Dongxu-Zheng
> 
> It is quite normal for transcript IDs to not match between transcriptomes, as they change between reference versions. However, IsoAnnotLite requires correspondence between genomic positions and/or gene IDs to transfer functional features to long read-defined isoforms. It seems to me that the GENCODE reference genome and GTF that you used are not compatible with ENSEMBL in neither of these aspects.
> 
> The solution would be to use a genome annotation and GTF for ENSEMBL to create your transcriptome, that is, from the beginning of your pipeline, or **at least** (*) to run SQANTI3. This will ensure that the long-read transcripts are matched to ENSEMBL genes and genomic positions. Then, you may use IsoAnnotLite to generate a functional annotation.
> 
> _**(*)** Note that, depending on the method you used to generate your transcriptome from long reads, you may also need to re-run the pipeline using the ENSEMBL genome and GTF. I would give re-running SQANTI3 with ENSEMBL reference files a go, but if it doesn't work, you'll need to start from scratch._
> 
> Let me know if this solved your problem so that we can use this info to improve support/documentation of our tools.
> 
> Best,
> 
> Ángeles

Hi Ángeles,

Thanks for your reply. My genome reference and annotation gtf files are coming from gencode website with the latest release. I just found that I can add some parameters, like: --isoAnnotLite --gff3 ./10_IsoAnnot/reference_genome_index/Homo_sapiens_GRCh38_Ensembl_86.gff3 when I run sqanti3_qc.py. Then I can get some result and some of my transcripts can be annotated. Do you think this is a good way to go? 

Cheers,
Dongxu

**Comment by aarzalluz** [comment]
Hi @Dongxu-Zheng,

To annotate your transcripts, please use an ENSEMBL reference to build your long-read transcriptome, and re-run IsoAnnotLite. As I explained in my previous comment, transferring functional features from tappAS' human ENSEMBL GFF3 will not work for GENCODE transcripts.

You will find information on use cases and instructions on how to run the script at the [IsoAnnotLite website](https://isoannot.tappas.org/isoannot-lite/).

Best,

Ángeles
