### ISSUE TITLE
DIU stuck on loading 

### ISSUE THREAD

**Issue by Ismail-Curie** [ConesaLab/tappAS#37]
Hello,
I have this issue when running Differential isoform usage, the results are stuck on loading screen with no errors, have you ever encountered the same issue.
Thank you very much.

**Comment by aarzalluz** [comment]
Hi @Ismail-Curie,

I have never experienced that issue. Could you provide application logs or more info to see if there is a specific error we can track?

Best,

Ángeles

**Comment by Ismail-Curie** [comment]
hi @aarzalluz,
I can't even visualize the analysis log on tappas for this specific analysis, this is the logs from the file tappas.log.

17:15 - Running Differential Isoform Usage Analysis...
17:26 - [WARN] Unable to find expression values for gene ''
17:26 - Transcripts DIU completed successfully.
17:27 - Unable to find gene for 54 expressed transcript(s).
17:27 - [WARN] Unable to find gene information for 1 genes.

Thank you,
Ismail

**Comment by aarzalluz** [comment]
@Ismail-Curie,

You can find log files for DIU analyses under the` /tappasWorkspace/Project/*projectID*/Data/DIU/` folder. There should be at least one file named `log.*.txt` there. Any chance you can track that down? It's going to be hard to debug otherwise.

Ángeles

**Comment by Ismail-Curie** [comment]
Hi @aarzalluz,
You will find attached the log file.
Thank you,
Ismail
[log_trans.txt](https://github.com/ConesaLab/tappAS/files/7569700/log_trans.txt)

**Comment by aarzalluz** [comment]
@Ismail-Curie,

Everything seems fine there -According to the log, results are computed and stored correctly. 

However, you do have a big expression matrix (~50K transcripts if I'm not mistaken). Have you tried running tappAS with more RAM? Instructions are available [at our FAQs section](at https://app.tappas.org/faqs/), just go to the **How do I run tappAS with more RAM?** question. Just make sure that you don't run the application with more RAM that is available on your machine.

Ángeles

**Comment by Ismail-Curie** [comment]
@aarzalluz,
I think that might be the problem, but it doesn't work even with more RAM, the output of SQANTI contains the transcripts from 21 samples, I tried to filter the count matrix but I think the real problem is the annotation file (542521 transcript), do you have any idea how and when to filter the gtf file from SQANTI.
Thank you,
Ismail

**Comment by aarzalluz** [comment]
@Ismail-Curie,

You can -and, more importantly, **should**- filter the GTF output by SQANTI3 using **quality control-related criteria**. That is, in fact, part of the recommended SQ3 workflow, since many of the transcripts output by long read tools are likely to be false-positive isoforms, sequencing artifacts, etc. You may also want to run some sort of **collapse** algorithm (Cupcake, TAMA, or other) to minimize the redundancy of your transcript models prior to running SQ3, and then filter using QC-related criteria. That would be my recommendation.

We currently have a wrapper for a rule-based filtering of isoforms (see the [Rules Filter page](https://github.com/ConesaLab/SQANTI3/wiki/Running-SQANTI3-rules-filter) in the SQ3 Wiki), but you can complement that with additional, user-defined rules for TSS, TTS, junctions, etc. See the [SQ3 ouptut explanation](https://github.com/ConesaLab/SQANTI3/wiki/SQANTI3-output-explanation) site for details. After filtering, please make sure that you quantify your transcripts again for accuracy and to avoid losing the reads of removed isoforms.

I hope that helps. Best,

Ángeles

PS: Since this is not longer tappAS-related question, I will close the issue now.
