### ISSUE TITLE
error in loading new project

### ISSUE THREAD

**Issue by CS791** [ConesaLab/tappAS#4]
Hi! 

I am trying to do tappAS analysis using my own data.
I got the following error. 

"20:38 - [ERROR] java.lang.IllegalStateException Code Exception: Not on FX application thread; currentThread = Thread-13
20:38 - Closing project 'BD'"

Any help is much appreciated.

Thanks
Saurabh

**Comment by psalguerog** [comment]
Dear Saurabh,

I have not enough information to completely understand your problem. If you can you should check your file structures (design and expression matrix) and compare it with the structure showed on the website https://app.tappas.org/overview/ (Project section).

I'm waiting for your answer with more information about your input files or I hope you had solved your problem.

Regards,

Pedro Salguero

**Comment by CS791** [comment]
Dear Pedro,

Please find the attached matrix and design file.

[1a_Matrix.txt](https://github.com/ConesaLab/tappAS/files/4732164/1a_Matrix.txt)
[1a_Design.txt](https://github.com/ConesaLab/tappAS/files/4732165/1a_Design.txt)

I am not sure where I am making mistake.

Thanks
Kind regards

Saurabh

**Comment by aarzalluz** [comment]
Hi @CS791,

Which one of tappAS supported species are you working with? I checked your files, and even though your design file is correct, the transcript names in your expression matrix do not seem to match the formatting for any of the species that we have annotations available for. I'm not sure whether this is the source of the error, but you should definitely make sure that these transcript names will be found in the annotation once the project is loaded -otherwise, project creation will fail.

Please note that we currently support RefSeq and ENSEMBL annotations for mouse and human, and ENSEMBL annotations for maize, drosophila and arabidopsis. For any other species (or for a PacBio transcriptome defined by the user), you'll need to provide your own functional annotation file in gff3 format.


Ángeles

**Comment by aarzalluz** [comment]
Hi @CS791,

It's been a long time, so I'm going to close the issue for now. I hope you found a solution to your problem. I would recommend reading through the installation instructions to check thtat you correctly install Java 8, R (+required packages) and tappAS, and referring to the tappAS website documentation for design file and expression matrix formatting information (you can find links to all these in the [README](https://github.com/ConesaLab/tappAS#readme)). 

Feel free to open a new issue or contact us via email if you run into any more problems.

Ángeles
