### ISSUE TITLE
Error while opening/installing tappAS

### ISSUE THREAD

**Issue by XiaoyuZhan520** [ConesaLab/tappAS#5]
Hi,

I think tappAS is very useful and try to apply it on my research. But I met some problems and wonder if you have any idea about them.

1. Source code
I wonder if you can provide the command to compile. It will be helpful if they are in READme file.

2. tappas.jar
I tried to run tappas.jar directly both in win10 and linux. 
In win10, I just double clipped the tappas.jar. But I failed because of the environment requirement. 
In linux, I run it with command 'java -Xmx3072M -jar  tappas.jar' . But it returned the error information 'Exception in thread "main" java.lang.reflect.InvocationTargetException'. 

I am a fresher in using java. Sorry to bother you. Many thanks in advance!

**Comment by psalguerog** [comment]
Dear Xiaoyu Zhan,

First of all, tappAS is a Java app and requires the Java installation to work properly. On tappAS webpage, you can find an [installation PDF](https://app.tappas.org/resources/downloads/install.pdf) with the instructions. 

Make sure you have installed the proper installation of Java (32 or 64 bits) for your computer and try to run it again. Also, sharing screenshots could help to identify the problem faster and add all the information you can relate to your computer.

Furthermore, if you are not sure if you are using the correct version of Java or not, you should do a reinstallation to be sure, downloading the newer version.

Try to follow the install pdf and reinstall the Java version. If that does not solve your problem try to add some screenshot about the different kind of errors and your computer features.

Regards,
Pedro Salguero

**Comment by XiaoyuZhan520** [comment]
Hi,

Thanks for your reply. 
I found that the requirement for R is "Rscript version 3.2.2 or later.".  However, some packages in R ("venn", maSigPro, etc,.)  depends R (≥ 3.5.0).

**Comment by psalguerog** [comment]
Dear Xiaoyu Zhan,

You're right. We recommend to install **Rscript 3.6** or later. You need, al least, that version to install all the dependencies. We also updated the install.pdf file.

Thank you,
Pedro Salguero

**Comment by XiaoyuZhan520** [comment]
Hello,

I have installed all required packages in R and open the .jar in Linux.
However, when I created new project, it returned the error information that 

added log txt(1): 12:54 - [ERROR] org.sqlite.SQLiteException Code Exception: [SQLITE_IOERR_FSYNC]  I/O error in the VFS layer while trying to flush previously written content (disk I/O error)

Do you have any idea about it? 

Many thanks!

Sincerely yours
Xiaoyu

**Comment by psalguerog** [comment]
Dear Xiaoyu Zhan,

It is the first time I see that kind of error in tappAS. I tell you different ways to try to fix it.

First, you have to be sure you have an admin account or one with permission to read and write in different folders. If you created your tappasWorkspace folder with one user account and switch to another can generate problems. Try to delete the tappasWorkspace folder and run tappAS again.

Also, if your problem is not solved by creating again the folder, check your Java version writing in a console:

`java --version`

tappAS was developed in Java 8 and if you have more than 4Gb of RAM (tappas requires 8Gb) we recommend to download a 64bit version of Java. You can find the different links [here](https://www.java.com/en/download/manual.jsp).

If your Java version is not the newest, uninstall it and download it again.

Regards,
Pedro Salguero

**Comment by aarzalluz** [comment]
Hi @XiaoyuZhan520,

I hope the information provided by @psalguerog helped you solve your problem -it's been a while, so I'm going to close the issue now. Please, feel free to open a new one or contact us via email if you run into any other problems or have questions about how to best analyze your data using tappAS.

Ángeles
