### ISSUE TITLE
SQANTI3 --IsoAnnotLite yields different gff3 files for different tissues when doing transcriptome comparative study

### ISSUE THREAD

**Issue by JoyzzzzzzZ** [ConesaLab/tappAS#51]
Dear Ángeles,

I am doing transcriptome study for the dog. I intend to look into differential gene expression and isoform usage between tissues and have got tappAS-compatible gff3 files by applying --IsoAnnotLite option when running SQANTI3. However, the gff3 files against different tissues are discrepant and of different sizes. So which gff3 should I use for differential analyses in tappAS to avoid inter-tissue bias? Thank you!

Joy

**Comment by aarzalluz** [comment]
Hi @JoyzzzzzzZ,

Based on what you're describing, it would be best to follow our [recommended long-read processing workflow](https://github.com/ConesaLab/SQANTI3/wiki/Introduction-to-SQANTI3#workflow). 

Briefly, I would recommend generating a single transcriptome for all of your tissues, and then quantifying using the data from each individual sample. In this manner, all isoforms, tissue specific or not, will be represented in your single transcriptome GFF3 file, which you will use to create the tappAS project. Since you quantified each sample, the expression values of these isoforms will vary across tissues, which is basically what you want to measure in the end.

I hope that helps! Best,

Ángeles
