### ISSUE TITLE
tx-import->DESeq2 pipeline excluded from DE analysis module

### ISSUE THREAD

**Issue by JamalEH** [ConesaLab/tappAS#7]
Dear Team,
Thank you again for the great tool, tappAS!

When running the nice tool on my RNA-seq datasets I realized that only edgeR and NOIseq packages were considered while DESeq2 was excluded from the DE module. Is there any rational behind this choice? Did you experience any out-performance of either edgeR or Noiseq over DESeq2 for DE analysis? or is it just a matter of personal choice of the normalization method "TMM" which is originally implemented in edgeR package?

Thank you so much in advance!
So far the tool's modules are working perfectly in my hands!

Best regards,
Jamal.

**Comment by aarzalluz** [comment]
Hi @JamalEH,

Sorry for the late response.

First, NOISeq is an R package for QC of RNA-Seq data and DE analysis that was developed by our group, and we routinely use it to perform our own analyses. We also included edgeR because it is one of the reference tools in the field, and even though it performs very similarly to DESeq2 (see [this blog post](https://mikelove.wordpress.com/2016/09/28/deseq2-or-edger/) by Mike Love for a more thorough description), it includes the TMM normalization method, as you mentioned. In fact, selecting TMM was no personal choice: it is one of the most suitable methods to normalize before DE analysis, and should be chosen over global scaling methods such as TPM or RPKM, which remove important differences between samples and should be used only for within-sample comparisons (see [our group's review paper](https://genomebiology.biomedcentral.com/articles/10.1186/s13059-016-0881-8) on best practices for RNA-Seq analysis for more info). NOISeq also includes the possibility to run edgeR's TMM function using a wrapper.

Finally, it has been shown that DESeq2 is less optimal in terms of runtime/memory efficiency in comparison to edgeR (see [this paper](https://genomebiology.biomedcentral.com/articles/10.1186/s13059-016-0881-8)). I've worked with both and I have to say that, for large datasets with many replicates and/or samples, it makes a huge difference to use edgeR.

This, however, does not mean that DESeq2 is not suitable for DE analysis, and we'll be happy to consider implementing DESeq2 in addition to edgeR and NOISeq in future versions of tappAS.

I'm closing the issue, but I hope you found this info useful. Feel free to contact us with any further questions or if you run into any issues while using tappAS.

Best,


Ángeles
