### ISSUE TITLE
Can I use my own gene annotation GTF file?

### ISSUE THREAD

**Issue by JamalEH** [ConesaLab/tappAS#9]
Hi,
Can I use a GTF/GFF3 file from Gencode v27 instead of the ones provided with the tool?

I tried using GTF file from Gencode  v27 but did not work properly. Do I need to pre-process this file prior to uploading it into tappAS?

Thank you in advance!
Kind regards,
Jamal.

**Comment by aarzalluz** [comment]
Hi, Jamal

You can potentially use any annotation file with tappAS. However, note that for that you will need to functionally annotate the file and re-format it as a tappAS-compatible GFF3. To make this easier for users, we currently provide pre-annotated gff3 files for ENSEMBL and RefSeq for mouse and human, but only for some annotation versions. I would recommend checking the [tappAS paper](https://genomebiology.biomedcentral.com/articles/10.1186/s13059-020-02028-w) for further information on transcriptome versions and the functional label categories they contain. If you quantify your transcriptomics data using any of those transcriptomes and the right version of the GTF file, you should have no problem loading your data into tappAS.

If, alternatively, you want to use your own version of the transcriptome, the only way around this is to use our **IsoAnnotLite** tool to transfer functional labels from our GFF3 files to your annotation file. However, please note that this is done based on genomic positions, and therefore some functional annotations may be lost in the process and/or some transcripts may remain unnanoted because they are not defined in our original files.

More information on how to use IsoAnnotLite with any annotation file can be found [here](https://isoannot.tappas.org/isoannot-lite/). FYI, IsoAnnotLite can also be run it directly with SQANTI3 for a user-defined long-read transcriptome via the the `--isoAnnotLite` argument (see SQANTI3 [README](https://github.com/ConesaLab/SQANTI3)). 

For Gencode, I would recommend transferring annotations from our ENSEMBL GFF3 file, which you can find [here](https://app.tappas.org/resources/downloads/gffs/). I apologize for any inconveniences -we are currently working on updating the transcriptome versions that are functionally annotated and readily available in tappAS, but this might still take a bit.


Ángeles

**Comment by JamalEH** [comment]
Dear Ángeles,
Thank you so much for your clear explanation! I appreciate that!

I will follow your instructions to get my own annotation works with tappAS.

Best regards,
Jamal.

**Comment by aarzalluz** [comment]
No worries! You're welcome. 

I'll leave the issue open for now, in case you have any more questions, but please let me know once you've completed the IsoAnnotLite run and managed to load your data into tappAS, and I will close it.

Ángeles
